pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    wedstrijdform:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 64
                                    forceResize: true
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 64
                                    forceResize: true
                        medias: {  }
                        name: wedstrijdform
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1664461873
                        creationDate: 1664461684
                        preserveAnimation: false
